### ISSUE TITLE
Add docker-compose

### ISSUE THREAD

**Issue by gEndelf** [jetbase-io/jetbase-rails#8]
It has to contain:
- postgres DB (data folders has to added as a volumes)
- backend itself
- **port** - use from wizard - during installation(_Which port would like your server to run? It should be unique to avoid port conflicts._)

**NOTE**: similar solution already available for node/express backend (see https://github.com/jetbase-io/jetbase-express-mongo/blob/feature/docker/docker-compose.yml)

**Comment by Raileanv** [comment]
done
